### ISSUE TITLE
Text rendering is not as sharp as in agg or gtk

### ISSUE THREAD

**Issue by andnovar** [andnovar/kivy#29]
![screenshot from 2015-07-10 02 44 53](https://cloud.githubusercontent.com/assets/400600/8613510/ff35e4da-26ad-11e5-8fa8-6a148bee436b.png)
![screenshot from 2015-07-10 02 46 04](https://cloud.githubusercontent.com/assets/400600/8613511/ff38c3b2-26ad-11e5-8db6-dab7ac38f6c3.png)

As can be seen some elements are blurry --> 25, 35 look not good.

**Comment by andnovar** [comment]
![screenshot from 2015-07-10 02 51 28](https://cloud.githubusercontent.com/assets/400600/8613591/a846a29e-26ae-11e5-9014-9892b72b56a9.png)

Normal kivy font ( Droid Sans ) --> still 25, 35 and 27 look not good

**Comment by Kovak** [comment]
The blurring on 25 and 35 are because the label is not sitting directly on an integer position but instead on a partial pixel (something like 50.35 or something). This causes GL to place a portion of the color on 50 and a portion of the color on 51 to simulate drawing the color directly at 50.35. The result is a 'blurred' looking character.

**Comment by andnovar** [comment]
I'll work with int positions then I'll let you know how it goes.

**Comment by andnovar** [comment]
You were right that fixed it :D :D :))))
