### ISSUE TITLE
mpl 1.5.1 (experimental) returns initial vertex point at the end of the list closing the path.

### ISSUE THREAD

**Issue by andnovar** [andnovar/kivy#56]

**Comment by andnovar** [comment]
It does it also in gtk

**Comment by matham** [comment]
Why are you closing this issue? Just because gtk also has that issue doesn't mean we don't need to deal with it. Either we need to find out if this is a bug, or more likely you're missing some instruction telling you something about the points. In either case, it's easy to deal with by checking the version and using the points accordingly.

**Comment by andnovar** [comment]
This is not a problem, the problem is the function I am using to get a string of the path, I did not really want to copy that code since there is something that already does that, but they change the name and even the arguments of the function from one version to another. Should I copy it ?

**Comment by matham** [comment]
Can you provide a side by side difference between the code? I.e. an example of code you'd use if we **only** supported 1.4.3 and similar code if we **only** supported 1.5.1. Because I still don't see the issue as to why you cannot exec different code depending on the mpl version.

Although you should still ask on their mailing list about this.
